[package]
name = "ponos-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
winnow = "0.6"
rustyline = "17.0.1"
once_cell = "1.20"
ordered-float = "4.0"
serde_json = "1.0"
ureq = { version = "2", features = ["json"] }
